//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NZEduEntities : DbContext
    {
        public NZEduEntities()
            : base("name=NZEduEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BannerInfo> BannerInfoes { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ImageInfo> ImageInfoes { get; set; }
        public DbSet<LoginInfo> LoginInfoes { get; set; }
        public DbSet<NewsInfo> NewsInfoes { get; set; }
    }
}
