//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerInfo
    {
        public int BannerID { get; set; }
        public string BannerName { get; set; }
        public string BannerExtension { get; set; }
        public Nullable<int> BannerSize { get; set; }
        public string BannerType { get; set; }
    }
}
namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}
namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageInfo
    {
        public int ImageID { get; set; }
        public string ImageName { get; set; }
        public string ImageExtension { get; set; }
        public Nullable<int> ImageSize { get; set; }
        public string ImageType { get; set; }
        public string ImageDescription { get; set; }
    }
}
namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInfo
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailID { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
    }
}
namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsInfo
    {
        public int NewsID { get; set; }
        public string NewsHeadline { get; set; }
        public string News { get; set; }
        public string NewsDate { get; set; }
    }
}
